// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError('Firebase is not supported on this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-Gd3rEUqF-vFV41zbJdwDirfxjOvNEcE',
    appId: '1:611798612784:web:16f4d7fbb3a5e3d6cd26f5',
    messagingSenderId: '611798612784',
    projectId: 'gccampusnavigation',
    authDomain: 'gccampusnavigation.firebaseapp.com',
    databaseURL: 'https://gccampusnavigation-default-rtdb.firebaseio.com',
    storageBucket: 'gccampusnavigation.firebasestorage.app',
    measurementId: 'G-50JYVJHG4K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbgG-qtM5MZukWwmdSC7i9J-5wjLlNYzg',
    appId: '1:611798612784:android:43d8bafa2f26c321cd26f5',
    messagingSenderId: '611798612784',
    projectId: 'gccampusnavigation',
    databaseURL: 'https://gccampusnavigation-default-rtdb.firebaseio.com',
    storageBucket: 'gccampusnavigation.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHB-D8rNOo6Myign1YWRXe2i4Oxscfsdc',
    appId: '1:611798612784:ios:0b6818122f74857dcd26f5',
    messagingSenderId: '611798612784',
    projectId: 'gccampusnavigation',
    databaseURL: 'https://gccampusnavigation-default-rtdb.firebaseio.com',
    storageBucket: 'gccampusnavigation.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHB-D8rNOo6Myign1YWRXe2i4Oxscfsdc',
    appId: '1:611798612784:ios:0b6818122f74857dcd26f5',
    messagingSenderId: '611798612784',
    projectId: 'gccampusnavigation',
    databaseURL: 'https://gccampusnavigation-default-rtdb.firebaseio.com',
    storageBucket: 'gccampusnavigation.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-Gd3rEUqF-vFV41zbJdwDirfxjOvNEcE',
    appId: '1:611798612784:web:d76c566d393f6370cd26f5',
    messagingSenderId: '611798612784',
    projectId: 'gccampusnavigation',
    authDomain: 'gccampusnavigation.firebaseapp.com',
    databaseURL: 'https://gccampusnavigation-default-rtdb.firebaseio.com',
    storageBucket: 'gccampusnavigation.firebasestorage.app',
    measurementId: 'G-BP3W5CRMDX',
  );

}